### ISSUE TITLE
Mindmap of OpenSSF Organizational structure (WGs, SIGs) and all known work products

### ISSUE THREAD

**Issue by mrutkows** [ossf/Diagrammers-Society#1]
Linked is the final version of the mindmap whose draft was shared during 11/17 meeting.  The plan is to review the final draft (remainder of the 3 WGs that were not completed by 11/17) and determine how we effectively "tag" and create action items against it.

https://drive.google.com/file/d/13USj2veOrYdkhvlqOEgfnZ1I_YIixrUS/view?usp=share_link

XMIND can be found in the Apple appstore: 
https://apps.apple.com/us/app/xmind-mind-map-brainstorm/id1286983622

Again, this was just a convenient tool I was introduced to at OWASP Foundation WGs and derivative works (formats) can use other formats for formal OSSF documentation/guides/etc.

**Comment by mrutkows** [comment]
Here is the PNG capture:
<img width="9849" alt="OpenSSF Structure" src="https://user-images.githubusercontent.com/7816715/205151176-40b41cdd-dc2d-41bb-83f6-91162ee29169.png">

**Comment by lehors** [comment]
For those who don't have a Mac you can download xmind from the main website: https://xmind.app It is available for the usual various systems.

Building on Matt's work and the discussion we had on the 12/15/22 call I massaged the map further to try and make it more compact. More can still be done but it's the end of the week so I'm posting what I've got. 

[OpenSSF - Organization Structure ALH shallow.xmind.zip](https://github.com/ossf/Diagrammers-Society/files/10248436/OpenSSF.-.Organization.Structure.ALH.shallow.xmind.zip)
Beware: you need to remove the .zip part of the filename. I just added that to get github to accept it as an attachment.

Of course there are many ways one can go with this kind of stuff but I also experimented with a different way of displaying the data (making listing some elements vertically) and I find the result pretty interesting.

[OpenSSF - Organization Structure ALH shallow vert.xmind.zip](https://github.com/ossf/Diagrammers-Society/files/10248444/OpenSSF.-.Organization.Structure.ALH.shallow.vert.xmind.zip)
(again, remove the .zip part of the filename)

Here is the PDF version: [Open SSF Organization Structure.pdf](https://github.com/ossf/Diagrammers-Society/files/10248449/Open.SSF.Organization.Structure.pdf)

**Comment by SecurityCRob** [comment]
thanks to Matt for putting this together.  Ideally this work will be leveraged as we go through our WG audit.
