### ISSUE TITLE
VOTE - Adopt SIG Charter

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/Diagrammers-Society#2]
Please review:
- the SIG Charter - https://github.com/ossf/Diagrammers-Society/blob/main/CHARTER.md 
- the SIG's Readme.md - https://github.com/ossf/Diagrammers-Society/blob/main/README.md
Provide feedback for desired changes and then express your vote to adopt the charter or refuse at this time by EoD 7Dec2022

**Comment by bobcallaway** [comment]
LGTM

**Comment by mrutkows** [comment]
+1 for charter, +1 README

**Comment by ran-dall** [comment]
+1 :white_check_mark: Approve

**Comment by SecurityCRob** [comment]
adopted by SIG 7dec2022
