### ISSUE TITLE
Security Toolbelt MSVR 1.0 / 404 message

### ISSUE THREAD

**Issue by TateGunning** [ossf/Diagrammers-Society#6]
### 404 Security Toolbelt MSVR 1.0
_Was on the OSSF Google Drive working document trying to identify the email list as recommended via previous Zoom call video, and received a 404 on click-through. Look forward to connecting further and enjoying the feedback. Thanks,_

**Comment by SecurityCRob** [comment]
Hi Tate.  The MVSR was merged into the Toolbelt's main readme file: https://github.com/ossf/toolbelt#mission   Which file were you in that liked to the old gdoc so I can correct that?

**Comment by TateGunning** [comment]
> Hi Tate. The MVSR was merged into the Toolbelt's main readme file: https://github.com/ossf/toolbelt#mission Which file were you in that liked to the old gdoc so I can correct that?

thanks boss @SecurityCRob
